arabic_number = str(input("Enter only 5 Arabic number: "))
arabic_number = arabic_number.replace('0','๐')
arabic_number = arabic_number.replace('1','๑')
arabic_number = arabic_number.replace('2','๒')
arabic_number = arabic_number.replace('3','๓')
arabic_number = arabic_number.replace('4','๔')
arabic_number = arabic_number.replace('5','๕')
arabic_number = arabic_number.replace('6','๖')
arabic_number = arabic_number.replace('7','๗')
arabic_number = arabic_number.replace('8','๘')
arabic_number = arabic_number.replace('9','๙')
print("Thai number is", arabic_number)