gender = input("Enter Gender (M/W): ")
if gender != 'M' and gender != 'W': print(gender,"is not M or W")
elif gender == 'M':
    year = int(input("Enter current year: "))
    bYear = int(input("Enter your birth year: "))
    weight = float(input("Enter your weight (kg): "))
    height = float(input("Enter your height (cm): "))
    print("- - - - - -")
    print("Your age =",year-bYear)
    print("Your BMI = {:.3f}".format(weight/((height/100)**2)))
    print("Your BMR = {:.3f}".format(66.5 + (13.75 * weight) + (5.003 * height) - (6.755 *(year-bYear))))
elif gender == 'W':
    year = int(input("Enter current year: "))
    bYear = int(input("Enter your birth year: "))
    weight = float(input("Enter your weight (kg): "))
    height = float(input("Enter your height (cm): "))
    print("- - - - - -")
    print("Your age =",year-bYear)
    print("Your BMI = {:.3f}".format(weight/((height/100)**2)))
    print("Your BMR = {:.3f}".format(655.1 + (9.563 * weight) + (1.850 * height) - (4.676 *(year-bYear))))